import { Lesson } from '@/types';

export const airfoilsLiftBasics: Lesson = {
  id: 'airfoils-lift-basics',
  topicId: 'airfoils-lift',
  title: 'Airfoils & Lift Generation',
  content: [
    {
      type: 'heading',
      level: 1,
      text: 'Introduction to Airfoils and Lift',
    },
    {
      type: 'paragraph',
      text: 'The wing is the component that makes flight possible. Understanding how an aerofoil generates lift is central to all of the Principles of Flight syllabus. This lesson covers aerofoil terminology, how lift is produced, the lift equation, and how changes in angle of attack and configuration affect lift and drag.',
    },
    {
      type: 'paragraph',
      text: 'A clear grasp of these concepts will help you understand why the aircraft behaves the way it does in different phases of flight, from takeoff through cruise to approach and landing.',
    },
    {
      type: 'heading',
      level: 1,
      text: 'Aerofoil Terminology',
    },
    {
      type: 'paragraph',
      text: 'Before discussing how lift is generated, you need to understand the key terms used to describe an aerofoil cross-section:',
    },
    {
      type: 'list',
      ordered: false,
      items: [
        'Leading edge - The front of the aerofoil, where the airflow first meets the wing',
        'Trailing edge - The rear of the aerofoil, where the airflow from the upper and lower surfaces rejoins',
        'Chord line - A straight line drawn from the leading edge to the trailing edge. Used as the reference for measuring angle of attack',
        'Camber - The curvature of the aerofoil. Upper camber is the curvature of the top surface, lower camber is the curvature of the bottom surface. The mean camber line lies halfway between the two',
        'Angle of attack (AoA) - The angle between the chord line and the relative airflow (the direction the air meets the wing). This is the most important factor the pilot can control to vary lift',
        'Relative airflow - The direction of the airflow relative to the wing, which is equal and opposite to the flight path of the aircraft',
      ],
    },
    {
      type: 'callout',
      variant: 'info',
      text: 'Angle of attack is NOT the same as pitch attitude. A wing can be at a high angle of attack even with the nose level or below the horizon, such as in a steep turn or during a pull-up from a descent.',
    },
    {
      type: 'heading',
      level: 1,
      text: 'How Lift Is Generated',
    },
    {
      type: 'paragraph',
      text: 'Lift generation is best explained by two complementary principles working together. Neither alone gives the complete picture:',
    },
    {
      type: 'heading',
      level: 2,
      text: 'Pressure Distribution (Bernoulli\'s Principle)',
    },
    {
      type: 'paragraph',
      text: 'As air flows over the curved upper surface of the aerofoil, it accelerates. Bernoulli\'s principle states that where the velocity of a fluid increases, its static pressure decreases. This creates a region of lower pressure above the wing. The pressure below the wing remains at or near ambient, so a net upward force is produced.',
    },
    {
      type: 'paragraph',
      text: 'Approximately two-thirds of the total lift is generated by the reduced pressure on the upper surface and one-third by the increased pressure on the lower surface.',
    },
    {
      type: 'heading',
      level: 2,
      text: 'Newton\'s Third Law (Reaction Force)',
    },
    {
      type: 'paragraph',
      text: 'The wing deflects the oncoming air downward (downwash). By Newton\'s third law, there is an equal and opposite reaction force pushing the wing upward. The greater the angle of attack, the more the air is deflected downward, and the greater the upward reaction force, up to the critical angle.',
    },
    {
      type: 'callout',
      variant: 'tip',
      text: 'Both Bernoulli and Newton are correct and complementary explanations for lift. In exam questions, either may be referenced. The pressure difference explanation is more commonly used in PPL theory.',
    },
    {
      type: 'heading',
      level: 1,
      text: 'Coefficient of Lift (CL)',
    },
    {
      type: 'paragraph',
      text: 'The coefficient of lift (CL) is a dimensionless number that represents the lifting effectiveness of an aerofoil at a given angle of attack. It depends primarily on the shape of the aerofoil and the angle of attack.',
    },
    {
      type: 'paragraph',
      text: 'As angle of attack increases from zero, CL increases approximately linearly. This continues until the critical (stalling) angle of attack, typically around 16 degrees for a conventional aerofoil, where CL reaches its maximum value (CL max). Beyond this angle, the airflow separates from the upper surface, CL drops sharply, and the wing stalls.',
    },
    {
      type: 'heading',
      level: 1,
      text: 'The Lift Equation',
    },
    {
      type: 'paragraph',
      text: 'The total lift produced by a wing is described by the lift equation:',
    },
    {
      type: 'callout',
      variant: 'info',
      text: 'L = CL x half-rho x V-squared x S. Where: L = Lift force, CL = Coefficient of lift (depends on AoA and aerofoil shape), rho = Air density, V = True airspeed, S = Wing area.',
    },
    {
      type: 'paragraph',
      text: 'This equation tells us that lift depends on four factors. The pilot can control CL (by changing angle of attack) and V (by changing speed). Air density (rho) varies with altitude and temperature. Wing area (S) is fixed for a given aircraft, unless Fowler flaps are extended.',
    },
    {
      type: 'list',
      ordered: false,
      items: [
        'Double the speed and lift increases by a factor of four (lift is proportional to V squared)',
        'At higher altitude, reduced air density means a higher true airspeed is needed for the same lift',
        'Increasing CL (raising the angle of attack) allows flight at a lower speed for the same lift',
      ],
    },
    {
      type: 'heading',
      level: 1,
      text: 'Angle of Attack and the CL Curve',
    },
    {
      type: 'paragraph',
      text: 'The CL versus angle of attack graph is one of the most important diagrams in Principles of Flight:',
    },
    {
      type: 'list',
      ordered: false,
      items: [
        'At zero angle of attack, a cambered aerofoil still produces some lift (positive CL)',
        'CL increases linearly with angle of attack through the normal flying range',
        'CL reaches its maximum (CL max) at the critical angle of attack, typically around 16 degrees',
        'Beyond the critical angle, the boundary layer separates from the upper surface, CL falls rapidly, and the wing is stalled',
        'The exact value of CL max and the critical angle depend on the aerofoil design',
      ],
    },
    {
      type: 'heading',
      level: 1,
      text: 'Drag',
    },
    {
      type: 'heading',
      level: 2,
      text: 'Induced Drag',
    },
    {
      type: 'paragraph',
      text: 'Induced drag is a consequence of producing lift. Because the pressure below the wing is higher than above, air spills around the wingtips from below to above, creating wingtip vortices. These vortices tilt the relative airflow downward, meaning the lift vector is tilted backward, creating a rearward drag component.',
    },
    {
      type: 'paragraph',
      text: 'Induced drag is greatest at high angles of attack and low speeds (when CL is high). It decreases as speed increases. It is proportional to CL squared.',
    },
    {
      type: 'heading',
      level: 2,
      text: 'Parasite Drag',
    },
    {
      type: 'paragraph',
      text: 'Parasite drag is all the drag not associated with the production of lift. It includes form drag (shape of the aircraft), skin friction drag (roughness of surfaces), and interference drag (where components meet, e.g., wing-fuselage junction). Parasite drag increases with the square of airspeed.',
    },
    {
      type: 'heading',
      level: 2,
      text: 'Total Drag and the Lift/Drag Ratio',
    },
    {
      type: 'paragraph',
      text: 'Total drag is the sum of induced drag and parasite drag. At low speeds, induced drag dominates. At high speeds, parasite drag dominates. There is an optimum speed where total drag is at its minimum. This speed also corresponds to the best lift-to-drag ratio (L/D max), which is important for best glide range.',
    },
    {
      type: 'callout',
      variant: 'tip',
      text: 'The speed for best L/D ratio is the speed for maximum range in a glide. It is also approximately the speed for best endurance in powered flight. This speed is often marked or referenced in the POH.',
    },
    {
      type: 'heading',
      level: 1,
      text: 'Effect of Flaps on the CL Curve',
    },
    {
      type: 'paragraph',
      text: 'Deploying flaps increases the camber of the aerofoil, which shifts the CL curve upward and to the left:',
    },
    {
      type: 'list',
      ordered: false,
      items: [
        'CL max increases, meaning more lift is available at a given speed, or the same lift at a lower speed',
        'The critical angle of attack decreases slightly (the wing stalls at a lower AoA with flaps deployed)',
        'Drag increases significantly, especially at large flap settings',
        'The net effect is a lower stall speed, which is why flaps are used for takeoff and landing',
      ],
    },
    {
      type: 'heading',
      level: 1,
      text: 'Centre of Pressure',
    },
    {
      type: 'paragraph',
      text: 'The centre of pressure (CP) is the point on the chord line where the total aerodynamic force (lift and drag) is considered to act. As the angle of attack changes, the pressure distribution over the wing changes, and the CP moves:',
    },
    {
      type: 'list',
      ordered: false,
      items: [
        'As angle of attack increases, the CP moves forward along the chord',
        'As angle of attack decreases, the CP moves rearward along the chord',
        'At the stall, the CP moves sharply rearward as the pressure distribution breaks down',
      ],
    },
    {
      type: 'callout',
      variant: 'info',
      text: 'The movement of the centre of pressure with angle of attack is why aircraft pitch stability is so important. If the CP moves ahead of the centre of gravity, it creates a nose-up pitching moment that could be destabilising.',
    },
    {
      type: 'heading',
      level: 1,
      text: 'Key Takeaways',
    },
    {
      type: 'list',
      ordered: false,
      items: [
        'Angle of attack is the angle between the chord line and the relative airflow, and is the primary means of controlling lift',
        'Lift is generated by the pressure difference between upper and lower surfaces (Bernoulli) and by deflecting air downward (Newton)',
        'The lift equation: L = CL x half-rho x V-squared x S - lift varies with the square of speed',
        'CL increases with angle of attack up to the critical angle (~16 degrees), then drops sharply at the stall',
        'Total drag = induced drag (decreases with speed) plus parasite drag (increases with speed)',
        'Flaps increase CL max and lower the stall speed, but also increase drag',
      ],
    },
  ],
  keyPoints: [
    'Angle of attack is the angle between the chord line and relative airflow - not the same as pitch attitude',
    'Lift equation: L = CL x half-rho x V-squared x S; lift varies with the square of airspeed',
    'CL max occurs at the critical angle of attack (~16 degrees); beyond this the wing stalls',
    'Induced drag is highest at low speed/high AoA; parasite drag is highest at high speed',
    'Best L/D ratio occurs at the speed where total drag is minimum',
    'Centre of pressure moves forward with increasing AoA and rearward at the stall',
  ],
  practiceQuestions: [
    'pof-006',
    'pof-007',
    'pof-008',
    'pof-009',
  ],
};
