import { Lesson } from '@/types';

export const fourForcesBasics: Lesson = {
  id: 'four-forces-basics',
  topicId: 'four-forces',
  title: 'Four Forces of Flight - Basics',
  content: [
    {
      type: 'heading',
      level: 1,
      text: 'Introduction to the Four Forces',
    },
    {
      type: 'paragraph',
      text: 'Four forces act on an aircraft in flight: Lift, Weight, Thrust, and Drag. Understanding how these forces interact is fundamental to understanding how and why aircraft fly.',
    },
    {
      type: 'callout',
      variant: 'info',
      text: 'In steady, level, unaccelerated flight, the four forces are in equilibrium: Lift = Weight, Thrust = Drag.',
    },
    {
      type: 'heading',
      level: 2,
      text: 'The Four Forces',
    },
    {
      type: 'paragraph',
      text: 'Each force acts in a specific direction:',
    },
    {
      type: 'list',
      ordered: false,
      items: [
        'Lift - Acts perpendicular to the relative airflow and the wing, generated by the wing',
        'Weight - Acts vertically downward through the centre of gravity, due to gravity',
        'Thrust - Acts forward in the direction of flight, generated by the engine/propeller',
        'Drag - Acts rearward, opposite to the direction of flight, resistance to motion through air',
      ],
    },
    {
      type: 'heading',
      level: 2,
      text: 'Lift',
    },
    {
      type: 'paragraph',
      text: 'Lift is the upward force generated by the wing as it moves through the air. It is perpendicular to the relative airflow. The amount of lift depends on:',
    },
    {
      type: 'list',
      ordered: false,
      items: [
        'Airspeed - Lift increases with the square of speed (double speed = 4× lift)',
        'Wing area - Larger wing produces more lift',
        'Air density - Higher density (low altitude, cold air) = more lift',
        'Angle of attack - Increasing angle of attack increases lift, up to the critical angle',
      ],
    },
    {
      type: 'callout',
      variant: 'tip',
      text: 'The wing generates lift by accelerating air downward (Newton\'s 3rd law) and by creating a pressure difference between upper and lower surfaces.',
    },
    {
      type: 'heading',
      level: 2,
      text: 'Weight',
    },
    {
      type: 'paragraph',
      text: 'Weight is the force of gravity acting on the aircraft\'s mass. It acts vertically downward through the centre of gravity. Weight is constant during flight, except as fuel is burned.',
    },
    {
      type: 'paragraph',
      text: 'To maintain level flight, lift must equal weight. If weight increases (e.g., heavier load), more lift is needed, which requires either higher speed or greater angle of attack.',
    },
    {
      type: 'heading',
      level: 2,
      text: 'Thrust',
    },
    {
      type: 'paragraph',
      text: 'Thrust is the forward force produced by the engine and propeller (or jet engine). It overcomes drag and provides the energy for flight.',
    },
    {
      type: 'paragraph',
      text: 'In level flight, thrust must equal drag. To accelerate, increase thrust. To climb, thrust must exceed drag. To descend at constant speed, reduce thrust below drag.',
    },
    {
      type: 'callout',
      variant: 'info',
      text: 'Propellers convert engine power into thrust. Propeller efficiency decreases with speed, which is why propeller aircraft have speed limits.',
    },
    {
      type: 'heading',
      level: 2,
      text: 'Drag',
    },
    {
      type: 'paragraph',
      text: 'Drag is the resistance to motion through the air. It acts opposite to the direction of flight. There are two main types:',
    },
    {
      type: 'list',
      ordered: false,
      items: [
        'Parasite drag - Increases with speed. Includes form drag (shape), skin friction, and interference drag',
        'Induced drag - Decreases with speed. Caused by the generation of lift (wingtip vortices). High at low speeds and high angles of attack',
      ],
    },
    {
      type: 'paragraph',
      text: 'Total drag is the sum of parasite and induced drag. There is a speed where total drag is minimum - this is the speed for best endurance and maximum lift-to-drag ratio.',
    },
    {
      type: 'heading',
      level: 2,
      text: 'Forces in Equilibrium',
    },
    {
      type: 'paragraph',
      text: 'In steady, straight, and level flight (no acceleration), the forces balance:',
    },
    {
      type: 'list',
      ordered: false,
      items: [
        'Lift = Weight (vertical equilibrium)',
        'Thrust = Drag (horizontal equilibrium)',
      ],
    },
    {
      type: 'paragraph',
      text: 'When forces are not in equilibrium, the aircraft accelerates in the direction of the net force:',
    },
    {
      type: 'list',
      ordered: false,
      items: [
        'Lift > Weight → Aircraft climbs',
        'Weight > Lift → Aircraft descends',
        'Thrust > Drag → Aircraft accelerates',
        'Drag > Thrust → Aircraft decelerates',
      ],
    },
    {
      type: 'callout',
      variant: 'warning',
      text: 'Lift does NOT make the aircraft climb. Excess thrust (or reducing drag) provides the energy for a climb.',
    },
    {
      type: 'heading',
      level: 2,
      text: 'Key Takeaways',
    },
    {
      type: 'list',
      ordered: false,
      items: [
        'Four forces: Lift (up), Weight (down), Thrust (forward), Drag (rearward)',
        'In level flight: Lift = Weight, Thrust = Drag',
        'Lift increases with speed, wing area, air density, and angle of attack',
        'Drag has two components: parasite drag (increases with speed) and induced drag (decreases with speed)',
        'Excess thrust provides the energy for climb, not excess lift',
      ],
    },
  ],
  keyPoints: [
    'Four forces: Lift, Weight, Thrust, Drag',
    'Level flight equilibrium: Lift = Weight, Thrust = Drag',
    'Lift depends on speed, wing area, air density, angle of attack',
    'Total drag = Parasite drag + Induced drag',
    'Climbing requires excess thrust to overcome drag and gain altitude',
  ],
  practiceQuestions: [
    'pof-001',
    'pof-002',
    'pof-003',
    'pof-004',
  ],
};
